### ISSUE TITLE
html translate -t en test.json 翻译成英文报错

### ISSUE THREAD

**Issue by JoffreyN** [F-loat/html-i18n-cli#1]
C:\~\File\2021-12>html translate -t en test.json
Cannot find module 'C:\~\File\2021-12\en'
Require stack:
- C:\~\npm\node_modules\html-i18n-cli\lib\translate.js
- C:\~\npm\node_modules\html-i18n-cli\bin\html.js

**Comment by F-loat** [comment]
试下 `html translate -t=en test.json`，目前没 windows 设备不好验证
